CREATE SCHEMA IF NOT EXISTS lab1;
USE lab1;

CREATE TABLE THEMEPARK (
    PARK_CODE    VARCHAR(10) NOT NULL PRIMARY KEY,
    PARK_NAME    VARCHAR(35) NOT NULL,
    PARK_CITY    VARCHAR(50) NOT NULL,
    PARK_COUNTRY CHAR(2)    NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMP_NUM       NUMERIC(4) NOT NULL PRIMARY KEY,
    EMP_TITLE     VARCHAR(4),
    EMP_LNAME     VARCHAR(15) NOT NULL,
    EMP_FNAME     VARCHAR(15) NOT NULL,
    EMP_DOB       DATE NOT NULL,
    EMP_HIRE_DATE DATE NOT NULL,
    EMP_AREACODE  VARCHAR(4) NOT NULL,
    EMP_PHONE     VARCHAR(12) NOT NULL,
    PARK_CODE     VARCHAR(10) NOT NULL,
    CHECK (EMP_NUM BETWEEN 0 AND 9999),
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK (PARK_CODE)
);

CREATE TABLE TICKET (
    TICKET_NO    NUMERIC(10) NOT NULL PRIMARY KEY,
    TICKET_PRICE NUMERIC(4, 2)  NOT NULL,
    TICKET_TYPE  VARCHAR(10)    NOT NULL,
    PARK_CODE    VARCHAR(10)    NOT NULL,
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK (PARK_CODE)
);

CREATE TABLE ATTRACTION (
    ATTRACT_NO       NUMERIC(10) NOT NULL PRIMARY KEY,
    PARK_CODE        VARCHAR(10)    NOT NULL,
    ATTRACT_NAME     VARCHAR(35)    NOT NULL,
    ATTRACT_AGE      NUMERIC(3)  NOT NULL DEFAULT 0,
    ATTRACT_CAPACITY NUMERIC(3)  NOT NULL,
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK (PARK_CODE)
);

CREATE TABLE HOUR (
    EMP_NUM           NUMERIC(4)  NOT NULL,
    ATTRACT_NO        NUMERIC(10) NOT NULL,
    HOURS_PER_ATTRACT NUMERIC(2)  NOT NULL,
    HOUR_RATE         NUMERIC(4, 2)  NOT NULL,
    DATE_WORKED       DATE           NOT NULL,
    PRIMARY KEY (EMP_NUM, ATTRACT_NO),
    FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE (EMP_NUM),
    FOREIGN KEY (ATTRACT_NO) REFERENCES ATTRACTION (ATTRACT_NO)
);

CREATE TABLE SALES (
    TRANSACTION_NO NUMERIC(10) NOT NULL PRIMARY KEY,
    PARK_CODE      VARCHAR(10)    NOT NULL,
    SALE_DATE      DATE           NOT NULL,
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK (PARK_CODE)
);

CREATE TABLE SALESLINE (
    TRANSACTION_NO NUMERIC NOT NULL,
    LINE_NO        NUMERIC(2)  NOT NULL,
    TICKET_NO      NUMERIC(10) NOT NULL,
    LINE_QTY       NUMERIC(4)  NOT NULL,
    LINE_PRICE     NUMERIC(9, 2)  NOT NULL,
    PRIMARY KEY (TRANSACTION_NO, LINE_NO),
    FOREIGN KEY (TRANSACTION_NO) REFERENCES SALES (TRANSACTION_NO),
    FOREIGN KEY (TICKET_NO) REFERENCES TICKET (TICKET_NO)
);
